subgraphs:
  alerts:
    routing_url: http://localhost:4401/
    schema:
      file: src/subgraphs/alerts/alerts-schema.graphql
  notices:
    routing_url: http://localhost:4402/
    schema:
      file: src/subgraphs/notices/notices-schema.graphql
  root:
    routing_url: http://localhost:4403/
    schema:
      file: src/subgraphs/root/root-schema.graphql
  users:
    routing_url: http://localhost:4404/
    schema:
      file: src/subgraphs/users/users-schema.graphql
